apiVersion: v1
kind: Service
metadata:
  name: {{ include "octoprint.fullname" . }}
  labels:
    app: {{ include "octoprint.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      port: 5000
      nodePort: 30001
      protocol: TCP
      name: http
  selector:
    app: {{ include "octoprint.name" . }}
